### ISSUE TITLE
Step 3 - Conda

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#111]
~~Fork vCDAT if you haven't already~~

    cd ~/projects/UV-CDAT
    git clone git@github.com:USERNAME/vcdat.git
    cd vcdat
    ./scripts/setup_mac.sh

If the setup script gives a error about vcs-widgests try this other wise skip
    source activate vcdat
    npm link vcs-widgets
    source deactivate
     ./scripts/setup_mac.sh

Now that you have a built ready version of vcdat we need to create a conda package and uploaded to your user account. (Notes from the white board, reminder commands are guesses) You may be able to try `man conda` of `conda -h` for command information. Our current version is `alpha.17.3.X` where X is the day of the month.

    conda build / pack
    conda publish <USERNAME> <Password> <Version>

Then Test that you can create and use that vCDAT build. There may be some vcd-widgets linking issues we need to sort out and document. I hope not. For this test it will be like Sam's example below

    rm -rf ~/andaconda/env/vcdat   (where ever that is)
    conda create -n vcdat -c USERNAME -c conda-forge -c uvcdat vcdat <version?>
    source activate vcdat
    vcdat

You'll know it worked if a browser window opens, worst case its just blue (react failed) or best case, it works!

Sam released a super-beta version of VCDAT on his personal conda channel.
 
    conda create -n vcdat -c chaosphere2112 -c conda-forge -c uvcdat vcdat
    source activate vcdat
    vcdat

**Comment by mattben** [comment]
Where did you put the documentation on this? What is the command to download it from your channel?

**Comment by SandiSamuel** [comment]
Hello Matt,

The documentation is under “Developing vcdat” in the wiki.

---Sandi

**Comment by mattben** [comment]
@SandiSamuel if this is what your referring, please convert this history print out to a written doc with step by step instructions for installation. 

https://github.com/UV-CDAT/vcdat/wiki/Deploying-vcdat
 
look at this page as an example. https://github.com/aims-group/intern/wiki/Start

**Comment by mattben** [comment]
Good Work 👍
