### ISSUE TITLE
vcdat won't if cdat needs to ask the anonymous question

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcdat#115]
vcdst script shoud set:
```
export UVCDAT_ANONYMOUS_LOG=True
```

**Comment by doutriaux1** [comment]
if not set typing `vcdat` just hangs w/o any prompt

**Comment by mattben** [comment]
fixed https://github.com/UV-CDAT/vcdat/commit/4d1dd1830ce0ec55f539b8b02d8cf50c80d0e9ce
