### ISSUE TITLE
variables browser needs improvements

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcdat#116]
* Cannot go up from directory where you staeted vcdat (or ${HOME} not sure) but I coudln
't access /
* when lot of files/directories we need sliders
* files in a directory are sorted more or less randomly (or it seems so), should be alphabetical and have options for time/alpha
* once you select a file you need to scroll to the bottom to click "add"

**Comment by doutriaux1** [comment]
* once you clicked `add` you need to click on file again to see the variables inside, we should have it doing that either when you click add a=or even better as you're browsing
* varialbes seem to be sorted by rank (good) but then randomly within this. Should be alphabetical

**Comment by doutriaux1** [comment]
* both files and variables should be selectables via double-click

**Comment by mattben** [comment]
adding to https://github.com/UV-CDAT/vcdat/projects/2

**Comment by mattben** [comment]
@matthewma7 I believe your current PR will close this issue
