### ISSUE TITLE
bad merge

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#120]
@doutriaux1 I merged your changes and than @SandiSamuel and I think some of your changes where over written. I just had @SandiSamuel pull from uvcdat/vcdat in to her fork. She has a clean master matching uvcadt/vcdat. Travis reported no errors. But she still has the vcs draw box, and the provenance error, which I believe is from using a strange broken nightly build of uvcdat and not 2.10.

Could you review the conda config, and setup scripts again and double check I didn't mess them up please.

**Comment by doutriaux1** [comment]
I'm on it. Now also note that this pushesto the `nigthly` channel so @SandiSamuel needs to create the env using that channel. I'll check that it actually uploaded anything as well

**Comment by mattben** [comment]
perfect, TIA (Thanks In Advance)

**Comment by doutriaux1** [comment]
@SandiSamuel I do not see the build.sh file anymore in the repo, somehow your PR removed it. nothing will be built w/o it. Let me put it back in. @mattben please make sure removed file are really meant to be removed before you merge next time.

**Comment by mattben** [comment]
@doutriaux1 @SandiSamuel yea my bad. I can't believe I merged them out of order 👎 on me

**Comment by mattben** [comment]
@doutriaux1 I'm working on cleaning up master to cut a pre-alpha and I believe I still have issues from merging out of order.

![screen shot 2017-06-20 at 4 23 20 am](https://user-images.githubusercontent.com/438922/27330964-59f50674-5570-11e7-9083-23e072fce5f8.png)

Im still getting the vcs box to pop up and I believe you corrected this, can you please fix again.

**Comment by mattben** [comment]
Thank You @doutriaux1 !!!!
