### ISSUE TITLE
File Explorer 

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#125]
Currently can only see the users home directly, this does not work if the data is on a external drive.

Need a way to go up a directory or start a root `\`

**Comment by doutriaux1** [comment]
@mattben did you take a look at this: https://scotch.io/tutorials/use-the-html5-file-api-to-work-with-files-locally-in-the-browser

**Comment by mattben** [comment]
@doutriaux1 Thank you for the link!! I definitely want to use this / something like this.

**Comment by mattben** [comment]
@matthewma7 I believe your current PR can close this issues too

**Comment by matthewma7** [comment]
@mattben Cool, I'll close it now.
