### ISSUE TITLE
Clicking Open

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#133]
Clicking open with out selecting a variable, will produce awesome errors in the console.

![image](https://user-images.githubusercontent.com/438922/28271605-d6437af0-6abd-11e7-91d5-9075a49eb933.png)

**Comment by mattben** [comment]
@matthewma7 I believe your PR will also close this issue

**Comment by matthewma7** [comment]
@mattben Yes, I think so. I'll close it now.

**Comment by mattben** [comment]
👍
