### ISSUE TITLE
New Color Theme

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#136]
Please switch color scheme to https://bootswatch.com/spacelab/

**Comment by matthewma7** [comment]
Simply switching to new theme without tweaking doesn't look good. So, maybe we want to formally decided on the theme first.

![chrome_2017-08-01_12-59-22](https://user-images.githubusercontent.com/3123478/28885829-378c2568-7785-11e7-9e79-e0555a1a291c.png)

**Comment by mattben** [comment]
That looks way better then before! if its easy to change the theme, could you demo a few of them in the meeting today @matthewma7 ?

**Comment by matthewma7** [comment]
Closed with PR https://github.com/UV-CDAT/vcdat/pull/140
