### ISSUE TITLE
cannot access vcs.js

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcdat#146]
when using vcdat on mac from a fresh conda build (on same computer) I cannot access localhost:8123 
![vcdat](https://user-images.githubusercontent.com/2781425/30336821-2ad2993e-979b-11e7-9140-f6c62ff22b1a.png)

anybody which process is suppose to serve on 8123, looks like this did not get started.
Although at times by continously clicking on it, I get through and then it works.

**Comment by matthewma7** [comment]
@doutriaux1, It seems you might not use the autorun.sh. @mattben may help to point out the docs for the exact steps to get the environment up and running.

**Comment by danlipsa** [comment]
@doutriaux1 Why 8123? autorun.sh has "vcs-server -p 8888 &" so the port should be 8888.

**Comment by danlipsa** [comment]
@doutriaux1 This is unrelated, but to use the latest features make sure you merge https://github.com/UV-CDAT/vcs-js/pull/14

**Comment by James-Crean** [comment]
Closing since this was solved.
