### ISSUE TITLE
Crash on second plot

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#149]
first plot displays as expected, but is triggering an error that makes the canvas read only thus a second plot can not over write the first. I first encountered a segfault from the python console, but not on the next 2 attempt. The JS console displays this.

<img width="1046" alt="screen shot 2017-10-18 at 4 40 18 am" src="https://user-images.githubusercontent.com/438922/31716946-e85b9a98-b3be-11e7-98b3-931eed3ba19e.png">

**Comment by James-Crean** [comment]
Looking into this more it looks like the input warning is unrelated. Inside CachedFiles.jsx is the following line: 

```
<FormControl className="full-width file-path" type="text" value={this.selectedFilePath} />
```

This just means that the user can't change the value by typing into the input. They need to actually select the file.

As for the crashing, I am also unable to produce a second plot regardless of what I do. Sometimes python crashes, but I have yet to find a way to get it to crash consistently.

Here is an example of a recent crash though:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 000000010afcc000-000000010afce000 [    8K] r-x/rwx SM=COW  /Users/USER/*/*.7

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libvtkWebCore-8.1.1.dylib         0x00000001152c538b vtkWebApplication::HandleInteractionEvent(vtkRenderWindow*, vtkWebInteractionEvent*) + 811
1   libvtkWebCorePython27D-8.1.1.dylib    0x00000001152ae63a PyvtkWebApplication_HandleInteractionEvent(_object*, _object*) + 170
2   libpython2.7.dylib                0x000000010b086ad3 PyEval_EvalFrameEx + 30627
3   libpython2.7.dylib                0x000000010b07eed2 PyEval_EvalCodeEx + 1666
```

**Comment by mattben** [comment]
fixed in vcs-js current PR
