### ISSUE TITLE
multiple panels

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/vcdat#158]
adding panels don't shrink
![vcdat2](https://user-images.githubusercontent.com/14208252/33284528-430c9356-d364-11e7-974c-5b08e7ac8a96.png)
 to fit

**Comment by James-Crean** [comment]
It looks like both the react code and vcs-js code are attempting to resize the canvas. I have opened [an issue](https://github.com/UV-CDAT/vcs-js/issues/20) for vcs-js to determine if there is a workaround for this. If not, we will need to determine which code base should be responsible for managing the canvas size.

**Comment by James-Crean** [comment]
Fixed in #177
