### ISSUE TITLE
Variable modification

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/vcdat#161]
It is not clear how to access the dimensions of a variable or to change them. Is this working? What if I want to make a 1d plot of the time history of a variable. Is this working?

**Comment by doutriaux1** [comment]
@glpotter the line I sent you actually grabs a very old version, i'm worki g on getting the newer packages on anaconda right now, will ping you when it's up and running.

**Comment by James-Crean** [comment]
Added in #174
