### ISSUE TITLE
Testing Framework Front End

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#19]
- Implement test framework.
- Write first test, and documentation on how to add a new test
  -  A test to make sure naming convention is followed (see README)
- Implement test coverage app
- update README with test coverage present badge

**Comment by embrown** [comment]
@mattben Everything but that damn badge!
Did you want me to do something like [this](http://maximilianschmitt.me/posts/istanbul-code-coverage-badge-github/)?
