### ISSUE TITLE
Old colormap palettes have strange colors toward the ends

### ISSUE THREAD

**Issue by James-Crean** [UV-CDAT/vcdat#217]
It looks like older colormaps provided by vcs often were smaller than the newer colormaps. As a result, the "ends" of the colormaps seem to be filled with random colors which makes users confused. Is there a fix for this @doutriaux1 ?

**Comment by doutriaux1** [comment]
this is due to these colormap being designed to use the range 16->239 whereas now we use the full range, eidting the graphic method will let user set the correct range
