### ISSUE TITLE
Stacked plots are different sizes

### ISSUE THREAD

**Issue by James-Crean** [UV-CDAT/vcdat#219]
@doutriaux1 

When stacking plots (e.g. boxfill with a vector/streamlines on top), the plots do not line up and/or they are not the same size. Are there templates that fix this already, do the users need to make their own, or is this a bug?

**Comment by doutriaux1** [comment]
if you'rte using clt and u/v then it's normal because they are on different grid and vcs uses the grid info to determine the domain if not set in the graphic method
