### ISSUE TITLE
setup_mac.sh broke

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#43]
I'm not sure if its because the nightly build of uvcdat is broke... but we get this error now.

    $ ./scripts/setup_mac.sh 
    NO CERT?
    ~/workbench/vcdat
    Installing requirements
    ~/workbench/vcdat ~/workbench/vcdat
    usage: conda [-h] [-V] [--debug] command ...
    conda: error: unrecognized arguments: file> # platform: osx-64 basemap=1.0.7=np19py27_0 cffi=1.6.0=py27_0 ...

**Comment by doutriaux1** [comment]
@mattben I've seen this with @chaosphere2112 last time we tried on my mac. This is due to the format of requirements.txt having changed. You need to either format requirements.txt to match the old format or edit the bit that parses it.

**Comment by mattben** [comment]
@doutriaux1 Thank you!
