### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#56]
@chaosphere2112 do you have a PR you need to submit?
since the split to the vcs-widgets there are some new bugs.

1. when you open a file, and click add or open the models do not close you have to click close which is not how it use to work.
2. dragging to the canvas is not generating plots
3. the browser console is flooded with 
`TypeError: this.canvas.clear is not a function. (In 'this.canvas.clear()', 'this.canvas.clear' is undefined)`

Can the three of us sit down later today and look at these. @embrown

**Comment by chaosphere2112** [comment]
@mattben You need to update your vcs-js package; either blow away your vcdat conda env and rerun setup, or do `conda upgrade -c chaosphere2112 vcs-js` with `vcdat` activated.

**Comment by embrown** [comment]
@chaosphere2112 is there a change we need to make to requirements.txt so that it gets the latest version of vcs-js?

**Comment by chaosphere2112** [comment]
@embrown Yeah, it looks like it installs =0.1 and I think I bumped the version up to 0.1.1; we should change it to <1 instead of =0.1
