### ISSUE TITLE
Errors with fresh setup (setup_mac.sh and autorun.sh)

### ISSUE THREAD

**Issue by embrown** [UV-CDAT/vcdat#57]
@chaosphere2112 @mattben  
Setting up a new machine, and I ran into a couple of errors which I thought should be documented.

1. I ran into this error on a fresh install of conda, running setup_mac.sh 
![screen shot 2016-11-16 at 8 27 20 am](https://cloud.githubusercontent.com/assets/5880275/20355582/a2bcd952-abd6-11e6-84e9-fabef330d5e0.png)
The fix was to do ```conda config --set ssl_verify false```.
I don't know if there's a more legitimate fix for this, or if there's some configuration step that I was missing, but I figured it might be good to note that I ran into this problem.

2. hadn't ever imported vcs in python, so I hadn't answered the question about logging user data. That resulted int he following error:
![screen shot 2016-11-16 at 8 22 07 am](https://cloud.githubusercontent.com/assets/5880275/20355324/cedf5dbc-abd5-11e6-8fbe-35c895d6a99b.png)
All I had to do was import vcs and answer the logging question.
Is there some way to disable this prompt so it doesn't break a fresh install?

**Comment by doutriaux1** [comment]
@embrown this might already been documented at: https://github.com/UV-CDAT/uvcdat/wiki/Install-using-Anaconda

I think it's mostly lab firewall related.

**Comment by chaosphere2112** [comment]
@embrown The `ssl_verify` thing is only true if you're here; we should probably assemble a gist or something of the setup of a new computer so we have that for interns (or it can get added to Matt's intern repo). As for the second thing, that's just UV-CDAT doing UV-CDAT things. Also should be added to the initial computer setup.
