### ISSUE TITLE
Add editor controls for the template labels

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/vcdat#64]
# Labels

All template attributes have a "priority" attribute; this controls the layer of the element. Lower priorities are further back; priority of 0 means the element is not drawn. For now you can have a hide/show checkbox that just sets the priority to 0 or 1 for any attribute.

Labels have 4 relevant attributes: x, y, `texttable`, and `textorientation`. For the sake of getting this project into users hands sooner than later, we'll settle for using pre-existing texttables and textorientations (which you can fetch using the same basic code as the ways that you get graphics methods, but sub in "texttable" or "textorientation"). X and Y control the position.

## Data-driven labels
 - dataname (The "id" attribute of the variable)
 - title (The "longname" or "title" attribute of the variable)
 - units (The units of the variable)
 - mean (Average value of the current plot)
 - min (Minimum value of the current plot)
 - max (Maximum value of the current plot)
 - file (If the "file" attribute is set, whatever value was in there)
 - crdate (The current date)
 - crtime (The current time)
 - zname (The name of the z axis; this will frequently be the time axis in a 3 dimensional variable)
 - tname (The name of the t axis; only shows up in a 4d var)
 - zvalue (The current value of the z axis we are viewing (used for animation); usually the same as crdate + crtime)
 - tvalue (The current value of the t axis we are viewing (if there are 4 dimensions); usually the same as crdate + crtime)
 - zunits (The units of the z axis)
 - tunits (The units of the t axis)

## Deprecated:
 - comment1 (Allows a user to specify an annotation on the plot. Replaced by textcombined objects now, though still should work.)
 - comment2 (Allows a user to specify an annotation on the plot. Replaced by textcombined objects now, though still should work.)
 - comment3 (Allows a user to specify an annotation on the plot. Replaced by textcombined objects now, though still should work.)
 - comment4 (Allows a user to specify an annotation on the plot. Replaced by textcombined objects now, though still should work.)
 - xvalue (Unused)
 - yvalue (Unused)
 - function (If the "function" attribute is set on the variable, will be displayed using this object as guidance.)
 - logicalmask (If the "logicalmask" attribute is set on the variable, will be displayed using this object as guidance.)
 - transformation ("" transformation "")
 - source ("" source "")

**Comment by chaosphere2112** [comment]
Depends on #63

**Comment by mattben** [comment]
Done https://github.com/UV-CDAT/vcdat/commit/f0037e66a9cce9b5a66c70f9b797fa444bab6355
