### ISSUE TITLE
Add editor controls for the template axis elements

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/vcdat#65]
# Axis Components

## Axis labels

These attributes have either an "x" or a "y" value, depending on if they're a "y" or "x" label respectively. This attribute controls the label's x or y position; the other coordinate is dictated by the tickmarks for the plot's axes.

 - xlabel1 (y only)
 - xlabel2 (y only)
 - ylabel1 (x only)
 - ylabel2 (x only)

## Axis tickmarks

Much like axis labels, these only have coordinates for a single axis. However, since they're lines, they actually have the left and right positions (or top and bottom) of the lines (x1/x2, y1/y2) depending on what axis they're associated with. mintics have no labels, tics do.

 - xtic1
 - xtic2
 - ytic1
 - ytic2
 - ymintic1
 - ymintic2

## Axis Titles

Simple labels that provide a title for an axis.

 - xname
 - yname

## Axis Units

Simple labels that provide the units for an axis.

 - xunits
 - yunits

**Comment by chaosphere2112** [comment]
Depends on #63

**Comment by mattben** [comment]
Done https://github.com/UV-CDAT/vcdat/commit/f0037e66a9cce9b5a66c70f9b797fa444bab6355
