### ISSUE TITLE
Probable leftover code to be removed

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/vcdat#87]
Found this: https://github.com/UV-CDAT/vcdat/blob/b6de78c44843574fc914b3dd7b9ca12cd37e8356/frontend/src/js/components/GMList.jsx#L12-L18

which seems to clash with this: https://github.com/UV-CDAT/vcdat/blob/b6de78c44843574fc914b3dd7b9ca12cd37e8356/frontend/src/js/components/GMList.jsx#L48-L56

I'm guessing the first one is leftover from the previous iteration where updateActiveGM was an action we used. Probably should be dropped now that it behaves internally.

**Comment by chaosphere2112** [comment]
@embrown Thoughts?

**Comment by embrown** [comment]
@chaosphere2112 Yeah, I think that updateActiveGM went from being passed in to GMList to originating in GMList. It should no longer be needed in GMList's props validation.

**Comment by embrown** [comment]
@chaosphere2112 though we DO need to add that validation back in here: https://github.com/UV-CDAT/vcdat/blob/b6de78c44843574fc914b3dd7b9ca12cd37e8356/frontend/src/js/components/modals/GraphicsMethodEditor.jsx#L5-L10
